/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./app/**/*.{js,ts,jsx,tsx,mdx}",
        "./pages/**/*.{js,ts,jsx,tsx,mdx}",
        "./components/**/*.{js,ts,jsx,tsx,mdx}",
    ],
    theme: {
        extend: {
            colors: {
                "on-surface-variant": "#434655",
                "surface-container": "#ededf9",
                "outline": "#737686",
                "surface-container-high": "#e7e7f3",
                "on-error": "#ffffff",
                "tertiary-fixed": "#ffdbcd",
                "on-tertiary-fixed": "#360f00",
                "on-surface": "#191b23",
                "surface-bright": "#faf8ff",
                "surface": "#faf8ff",
                "error-container": "#ffdad6",
                "on-primary-container": "#eeefff",
                "surface-container-highest": "#e1e2ed",
                "tertiary": "#943700",
                "primary-fixed": "#dbe1ff",
                "on-tertiary-container": "#ffede6",
                "on-primary-fixed-variant": "#003ea8",
                "on-secondary-fixed": "#0b1c30",
                "secondary-container": "#d0e1fb",
                "surface-container-low": "#f3f3fe",
                "surface-variant": "#e1e2ed",
                "on-primary": "#ffffff",
                "on-background": "#191b23",
                "on-secondary-container": "#54647a",
                "on-secondary": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "on-error-container": "#93000a",
                "surface-dim": "#d9d9e5",
                "error": "#ba1a1a",
                "primary-container": "#2563eb",
                "primary": "#004ac6",
                "outline-variant": "#c3c6d7",
                "secondary": "#505f76",
                "on-primary-fixed": "#00174b",
                "primary-fixed-dim": "#b4c5ff",
                "brand-dark": "#1a1f2e",
            },
            spacing: {
                "xs": "4px",
                "sm": "8px",
                "md": "16px",
                "lg": "24px",
                "xl": "48px",
                "xxl": "80px",
                "gutter": "24px",
            },
            fontSize: {
                "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
                "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
                "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
                "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
                "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
                "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
                "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.015em", fontWeight: "600" }],
                "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
            },
            maxWidth: {
                "container-max": "1280px",
            },
        },
    },
    plugins: [],
};